#!/bin/sh

### BEGIN INIT INFO
# Provides:          extensionManager
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: extensionManager
# Description:       extensionManager start-stop-daemon - Debian
### END INIT INFO

NAME="extensionManager"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/"

# Path to the binary
APPBIN="/home/johan/bin/extensionManager"
APPARGS=""

# User to run as
USER="johan"
# Group to run as 
GROUP="johan"

# Where the extensions will be stored
export PIXEXT_PATH=/home/johan/pixext/
# Hostname or IP and the post to this server
export PIXEXT_HOSTNAME=localhost:8080
# Mysql schema name
export PIXEXT_MYSQL_DB=extensionmanager
# Mysql host
export PIXEXT_MYSQL_HOST=sture.pixpro.net
# Mysql port
export PIXEXT_MYSQL_PORT=3306
# Mysql user
export PIXEXT_MYSQL_USER=
# Mysql pass
export PIXEXT_MYSQL_PASS=
# Shared server with pixext
export PIXEXT_SECRET=
# Mysql table prefix
export PIXEXT_JOOMLA_PREFIX=jos_


# Include functions 
set -e
. /lib/lsb/init-functions

start() {
  printf "Starting '$NAME'... "
  start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/$NAME.pid --chdir "$APPDIR" --exec "$APPBIN" -- $APPARGS || true
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done 
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
